"""empty message

Revision ID: 8c6cea348319
Revises: None
Create Date: 2016-11-17 21:45:32.616547

"""

# revision identifiers, used by Alembic.
revision = '8c6cea348319'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fighters', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('fighters', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('fighters', sa.Column('no_contest', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fighters', 'no_contest')
    op.drop_column('fighters', 'height')
    op.drop_column('fighters', 'age')
    ### end Alembic commands ###
